package it.android.servarium.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val primaryDark = Color(0xFFBEC2FF)
val onPrimaryDark = Color(0xFF262B61)
val primaryContainerDark = Color(0xFF3D4279)
val onPrimaryContainerDark = Color(0xFFE0E0FF)
val secondaryDark = Color(0xFFC5C4DD)
val onSecondaryDark = Color(0xFF2E2F42)
val secondaryContainerDark = Color(0xFF444559)
val onSecondaryContainerDark = Color(0xFFE1E0F9)
val tertiaryDark = Color(0xFFE7B9D5)
val onTertiaryDark = Color(0xFF45263C)
val tertiaryContainerDark = Color(0xFF5E3C53)
val onTertiaryContainerDark = Color(0xFFFFD7EE)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE4E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE4E1E9)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC7C5D0)
val outlineDark = Color(0xFF91909A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E1E9)
val inverseOnSurfaceDark = Color(0xFF303036)
val inversePrimaryDark = Color(0xFF555A92)
val surfaceDimDark = Color(0xFF131318)
val surfaceBrightDark = Color(0xFF39393F)
val surfaceContainerLowestDark = Color(0xFF0E0E13)
val surfaceContainerLowDark = Color(0xFF1B1B21)
val surfaceContainerDark = Color(0xFF1F1F25)
val surfaceContainerHighDark = Color(0xFF2A292F)
val surfaceContainerHighestDark = Color(0xFF34343A)

val primaryDarkMediumContrast = Color(0xFFD8D9FF)
val onPrimaryDarkMediumContrast = Color(0xFF1B2055)
val primaryContainerDarkMediumContrast = Color(0xFF878CC8)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFDBDAF3)
val onSecondaryDarkMediumContrast = Color(0xFF232437)
val secondaryContainerDarkMediumContrast = Color(0xFF8E8FA6)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFFECFEB)
val onTertiaryDarkMediumContrast = Color(0xFF391B31)
val tertiaryContainerDarkMediumContrast = Color(0xFFAE849F)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF131318)
val onBackgroundDarkMediumContrast = Color(0xFFE4E1E9)
val surfaceDarkMediumContrast = Color(0xFF131318)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF46464F)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDDDBE6)
val outlineDarkMediumContrast = Color(0xFFB2B1BB)
val outlineVariantDarkMediumContrast = Color(0xFF908F99)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE4E1E9)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A292F)
val inversePrimaryDarkMediumContrast = Color(0xFF3E437A)
val surfaceDimDarkMediumContrast = Color(0xFF131318)
val surfaceBrightDarkMediumContrast = Color(0xFF44444A)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF07070C)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1D23)
val surfaceContainerDarkMediumContrast = Color(0xFF27272D)
val surfaceContainerHighDarkMediumContrast = Color(0xFF323238)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D3D43)

val primaryDarkHighContrast = Color(0xFFF0EEFF)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFB9BEFD)
val onPrimaryContainerDarkHighContrast = Color(0xFF00023A)
val secondaryDarkHighContrast = Color(0xFFF0EEFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC1C1D9)
val onSecondaryContainerDarkHighContrast = Color(0xFF080A1B)
val tertiaryDarkHighContrast = Color(0xFFFFEBF4)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFE3B6D1)
val onTertiaryContainerDarkHighContrast = Color(0xFF1B0315)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF131318)
val onBackgroundDarkHighContrast = Color(0xFFE4E1E9)
val surfaceDarkHighContrast = Color(0xFF131318)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF46464F)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF1EEFA)
val outlineVariantDarkHighContrast = Color(0xFFC3C1CC)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE4E1E9)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF3E437A)
val surfaceDimDarkHighContrast = Color(0xFF131318)
val surfaceBrightDarkHighContrast = Color(0xFF504F56)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1F1F25)
val surfaceContainerDarkHighContrast = Color(0xFF303036)
val surfaceContainerHighDarkHighContrast = Color(0xFF3B3B41)
val surfaceContainerHighestDarkHighContrast = Color(0xFF47464C)







